version: '3.7'

services:
  ui:
    container_name: hn_ui_react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
